# Generated by Django 5.1.4 on 2024-12-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Title', models.CharField(max_length=200)),
                ('Author_Name', models.CharField(max_length=100)),
                ('Year', models.IntegerField()),
                ('Genre', models.CharField(max_length=100)),
            ],
        ),
    ]
